name: umeng_analytics_plugin
description: A Umeng analytics Flutter plugin support both android and ios. Umeng is a popular App analytics product in China.
version: 2.1.0
homepage: https://gitlab.brainco.cn/flutter/umeng_analytics_plugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tech.jitao.umeng_analytics_plugin
        pluginClass: UmengAnalyticsPlugin
      ios:
        pluginClass: UmengAnalyticsPlugin
